// This file was auto-generated by ML.NET Model Builder. 

using Microsoft.ML.Data;

namespace FDM
{
    public class ModelInput
    {
        [ColumnName("X[m]"), LoadColumn(0)]
        public float X_m_ { get; set; }


        [ColumnName("Y[m]"), LoadColumn(1)]
        public float Y_m_ { get; set; }


        [ColumnName("Displacement[cm]"), LoadColumn(2)]
        public float Displacement_cm_ { get; set; }


    }
}
